import './Help.css'
import { Link } from 'react-router-dom'

export default function Help() {
  return (
    <div className="container">
      <div className="form-wrapper">

        {/* Header */}
        <div className="header">
          <h1>How This Prediction Works</h1>
          <p className="subtitle">
            Understanding the data, models, and limitations of this system
          </p>
        </div>

        <div className="help-content">

          {/* Disclaimer */}
          <section className="help-section">
            <h2>Important Disclaimer</h2>
            <p>
              This application is an <strong>informational screening tool</strong>,
              not a medical diagnostic system. It does <strong>not</strong> replace
              professional medical advice, diagnosis, or treatment.
            </p>
            <p>
              The predictions shown here are generated by machine learning models
              trained on historical datasets. They indicate statistical risk patterns,
              not confirmed medical conditions. <strong>Always consult a qualified healthcare
              professional if you are concerned about your health.</strong>
            </p>
          </section>

          {/* Symptoms */}
          <section className="help-section">
            <h2>Symptoms & Risk Factors Used</h2>
            <p>
              The following inputs were selected based on their statistical
              relationship with lung cancer cases in the training data.
              Individual symptoms alone do not indicate cancer, but certain
              combinations may increase risk estimates.
            </p>

            <div className="symptom-list">
              <Symptom
                title="Gender"
                description="Biological sex may influence lung cancer risk due to differences in hormonal factors, occupational exposure, and smoking patterns observed in population studies."
              />
              <Symptom
                title="Age"
                description="Lung cancer risk increases with age due to cumulative exposure to environmental risk factors and long-term cellular damage."
              />
              <Symptom
                title="Smoking"
                description="The strongest known risk factor for lung cancer. Tobacco smoke contains carcinogens that cause long-term damage to lung tissue."
              />
              <Symptom
                title="Yellow Fingers"
                description="Yellow staining on fingers is often associated with long-term smoking and repeated exposure to tobacco toxins."
              />
              <Symptom
                title="Anxiety"
                description="Chronic anxiety may correlate with unhealthy coping behaviors such as smoking and increased sensitivity to physical symptoms."
              />
              <Symptom
                title="Peer Pressure"
                description="Social influence can contribute to risky behaviors like smoking initiation or continuation."
              />
              <Symptom
                title="Chronic Disease"
                description="Existing long-term medical conditions may increase vulnerability or overlap with respiratory health issues."
              />
              <Symptom
                title="Fatigue"
                description="Persistent fatigue can be a non-specific symptom associated with systemic illness or reduced oxygen efficiency."
              />
              <Symptom
                title="Allergy"
                description="Chronic allergies may cause ongoing airway inflammation, complicating respiratory health assessment."
              />
              <Symptom
                title="Wheezing"
                description="A whistling sound during breathing often associated with airway narrowing or inflammation."
              />
              <Symptom
                title="Alcohol Consumption"
                description="Excessive alcohol intake may indirectly increase cancer risk by weakening immune defenses and amplifying the effects of smoking."
              />
              <Symptom
                title="Coughing"
                description="A persistent cough is one of the most commonly reported early symptoms in lung cancer cases."
              />
              <Symptom
                title="Shortness of Breath"
                description="Difficulty breathing may indicate reduced lung capacity or obstruction within the airways."
              />
              <Symptom
                title="Swallowing Difficulty"
                description="Difficulty swallowing may result from pressure or irritation affecting nearby structures in the chest."
              />
              <Symptom
                title="Chest Pain"
                description="Ongoing chest discomfort can be linked to lung, pleural, or thoracic involvement."
              />
            </div>
          </section>

          {/* Feature Engineering */}
          <section className="help-section">
            <h2>How Your Data Is Processed</h2>
            <p>
              Before making predictions, the system derives additional indicators
              from your answers:
            </p>
            <ul>
              <li>
                <strong>Symptom Count:</strong> Total number of reported risk-related symptoms.
              </li>
              <li>
                <strong>Respiratory Score:</strong> Focuses specifically on breathing-related symptoms.
              </li>
              <li>
                <strong>Age Risk:</strong> A binary indicator that increases weight for higher-risk age groups.
              </li>
            </ul>
            <p>
              These engineered features help the models capture relationships that
              may not be obvious when evaluating individual symptoms alone.
            </p>
          </section>

          {/* Models */}
          <section className="help-section">
            <h2>How the Models Make Predictions</h2>
            <p>
              This system uses an <strong>ensemble of multiple machine learning models</strong>.
              Each model evaluates risk independently using different mathematical approaches.
            </p>

            <ul>
              <li>
                <strong>XGBoost:</strong> A gradient-boosted decision tree model that excels at identifying complex nonlinear relationships.
              </li>
              <li>
                <strong>Support Vector Machine (SVM):</strong> A model that separates risk groups using optimal decision boundaries in high-dimensional space.
              </li>
              <li>
                <strong>Neural Network:</strong> A deep learning model that learns layered representations of symptom interactions.
              </li>
            </ul>

            <p>
              Each model produces a probability score representing its estimate of
              lung cancer risk.
            </p>
          </section>

          {/* Ensemble Logic */}
          <section className="help-section">
            <h2>How the Final Prediction Is Made</h2>
            <p>
              This system uses multiple machine learning models that independently
              estimate lung cancer risk. Their probability outputs are combined
              to produce a final risk score.
            </p>
            <p>
              The final result is categorized into <strong>low</strong>,
              <strong> medium</strong>, or <strong>high</strong> risk based on
              the combined probability.
            </p>
          </section>

          {/* Risk Levels */}
          <section className="help-section">
            <h2>Understanding Risk Levels</h2>
            <ul>
              <li>
                <strong>Low Risk:</strong> No strong statistical indicators detected.
              </li>
              <li>
                <strong>Medium Risk:</strong> Some indicators present; monitoring or consultation may be advisable.
              </li>
              <li>
                <strong>High Risk:</strong> Multiple indicators detected; professional medical evaluation is strongly recommended.
              </li>
            </ul>
          </section>

          {/* Limitations */}
          <section className="help-section">
            <h2>Limitations of This System</h2>
            <p>
              Machine learning models are limited by the quality and scope of their
              training data. This system:
            </p>
            <ul>
              <li>Cannot detect cancer directly</li>
              <li>Does not use imaging or laboratory results</li>
              <li>May be biased by data availability and reporting accuracy</li>
            </ul>
            <p>
              <strong>Results should always be interpreted with caution and context.</strong>
            </p>
          </section>

          {/* Back */}
          <div className="help-actions">
            <Link to="/Predict-Lung-Cancer/" className="btn btn-primary result-btn">
              Back to Prediction
            </Link>
          </div>

        </div>
      </div>
    </div>
  )
}

function Symptom({ title, description }) {
  return (
    <div className="symptom-card">
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  )
}
